/**
 * Tailwind CSS config v1.8.2, 5.9.20
 * list of all plugins: https://tailwindcss.com/docs/configuration#core-plugins
 */
module.exports = {
  prefix: "tw-",
  important: true,
  separator: ":",
  theme: {
    screens: {},
    colors: {},
    spacing: {
      px: "1px",
      "0": "0",
      "12": "0.125rem",
      "25": "0.25rem",
      "50": "0.5rem",
      "75": "0.75rem",
      "100": "1rem",
      "125": "1.25rem",
      "150": "1.5rem",
      "200": "2rem",
      "250": "2.5rem",
      "300": "3rem",
      "400": "4rem",
      // "500": "5rem",
      // "600": "6rem",
      // "800": "8rem"
    },
    fontSize: {
      "50": "0.50rem",
      "65": "0.65rem",
      "75": "0.75rem",
      "85": "0.85rem",
      "14px": "0.875rem",
      base: "1rem", // 14px or 16px
      "110": "1.1rem",
      "125": "1.25rem",
      "150": "1.5rem",
      "175": "1.75rem",
      "200": "2.0rem",
      "250": "2.5rem",
    },
    fontWeight: {
      hairline: "100",
      thin: "200",
      light: "300", // use
      normal: "400", // use
      medium: "500",
      semibold: "600", // use
      bold: "700", // use
      extrabold: "800",
      black: "900",
    },
    height: theme => ({
      auto: "auto",
      //...theme("spacing"),
      full: "100%",
      screen: "100vh",
    }),
    listStyleType: {
      none: "none",
      disc: "disc",
      decimal: "decimal",
    },
    margin: (theme, { negative }) => ({
      auto: "auto",
      ...theme("spacing"),
      ...negative(theme("spacing")),
    }),
    maxWidth: {
      full: "100%",
    },
    opacity: {
      "0": "0",
      "25": "0.25",
      "33": "0.33",
      "50": "0.5",
      "66": "0.66",
      "75": "0.75",
      "90": "0.9",
      "100": "1",
    },
    width: theme => ({
      auto: "auto",
      //...theme("spacing"),
      "1/2": "50%",
      "1/3": "33.333333%",
      "2/3": "66.666667%",
      "1/4": "25%",
      "2/4": "50%",
      "3/4": "75%",
      "1/5": "20%",
      "2/5": "40%",
      "3/5": "60%",
      "4/5": "80%",
      "1/6": "16.666667%",
      "2/6": "33.333333%",
      "3/6": "50%",
      "4/6": "66.666667%",
      "5/6": "83.333333%",
      "1/12": "8.333333%",
      "2/12": "16.666667%",
      "3/12": "25%",
      "4/12": "33.333333%",
      "5/12": "41.666667%",
      "6/12": "50%",
      "7/12": "58.333333%",
      "8/12": "66.666667%",
      "9/12": "75%",
      "10/12": "83.333333%",
      "11/12": "91.666667%",
      full: "100%",
      screen: "100vw",
    }),
    zIndex: {
      auto: "auto",
      "0": "0",
      "10": "10",
      "20": "20",
      "30": "30",
      "40": "40",
      "50": "50",
    },
    borderRadius: {
      none: "0",
      "12": ".125rem",
      default: ".25rem",
      "50": ".5rem",
      "100": "1rem",
      full: "9999px",
      "4px": "4px",
    },
    borderWidth: {
      default: "1px",
      "0": "0",
    },
    extend: {},
  },
  variants: {
    alignContent: ["default"],
    alignItems: ["default"],
    alignSelf: ["default"],
    animation: ["default"],
    backgroundAttachment: ["default"],
    backgroundPosition: ["default"],
    backgroundRepeat: ["default"],
    backgroundSize: ["default"],
    borderCollapse: ["default"],
    borderRadius: ["default"],
    borderWidth: ["default"],
    boxShadow: ["default", "hover", "focus"],
    container: ["default"],
    cursor: ["default"],
    display: ["default", "hover"],
    flex: ["default"],
    flexDirection: ["default"],
    flexGrow: ["default"],
    flexShrink: ["default"],
    flexWrap: ["default"],
    float: ["default"],
    fontSize: ["default"],
    fontSmoothing: ["default"],
    fontStyle: ["default"],
    fontWeight: ["default", "hover", "focus"],
    gridAutoFlow: ["default"],
    gridColumn: ["default"],
    gridColumnEnd: ["default"],
    gridColumnStart: ["default"],
    gridRow: ["default"],
    gridRowEnd: ["default"],
    gridRowStart: ["default"],
    gridTemplateColumns: ["default"],
    gridTemplateRows: ["default"],
    height: ["default"],
    inset: ["default"],
    justifyContent: ["default"],
    justifyItems: ["default"],
    justifySelf: ["default"],
    letterSpacing: ["default"],
    lineHeight: ["default"],
    listStylePosition: ["default"],
    listStyleType: ["default"],
    margin: ["default"],
    maxHeight: ["default"],
    maxWidth: ["default"],
    minHeight: ["default"],
    minWidth: ["default"],
    objectFit: ["default"],
    objectPosition: ["default"],
    opacity: ["default", "hover", "focus"],
    order: ["default"],
    outline: ["default", "focus"],
    overflow: ["default"],
    padding: ["default"],
    pointerEvents: ["default"],
    position: ["default"],
    resize: ["default"],
    stroke: ["default"],
    tableLayout: ["default"],
    textAlign: ["default"],
    textDecoration: ["default", "hover", "focus"],
    textTransform: ["default"],
    userSelect: ["default"],
    verticalAlign: ["default"],
    visibility: ["default"],
    whitespace: ["default"],
    width: ["default"],
    wordBreak: ["default"],
    zIndex: ["default"],
  },
  corePlugins: {
    preflight: false,
    accessibility: false,
    appearance: false,
    backgroundClip: false,
    backgroundColor: false,
    backgroundImage: false,
    backgroundOpacity: false,
    borderColor: false,
    borderOpacity: false,
    borderStyle: false,
    boxSizing: false,
    clear: false,
    divideColor: false,
    divideOpacity: false,
    divideStyle: false,
    divideWidth: false,
    fill: false,
    fontFamily: false,
    fontVariantNumeric: false,
    gap: false,
    gradientColorStops: false,
    overscrollBehavior: false,
    placeContent: false,
    placeholderColor: false,
    placeholderOpacity: false,
    placeItems: false,
    placeSelf: false,
    rotate: false,
    scale: false,
    skew: false,
    space: false,
    strokeWidth: false,
    textColor: false,
    textOpacity: false,
    transform: false,
    transformOrigin: false,
    transitionDelay: false,
    transitionDuration: false,
    transitionProperty: false,
    transitionTimingFunction: false,
    translate: false,
  },
  plugins: [],
}
